# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_del_by_id_del_delete(self):
        """Test case for del_by_id_del_delete

        Del By Id  # noqa: E501
        """
        pass

    def test_edit_user_edit_put(self):
        """Test case for edit_user_edit_put

        Edit User  # noqa: E501
        """
        pass

    def test_id_list_list_get(self):
        """Test case for id_list_list_get

        Id List  # noqa: E501
        """
        pass

    def test_init_init_get(self):
        """Test case for init_init_get

        Init  # noqa: E501
        """
        pass

    def test_new_user_create_post(self):
        """Test case for new_user_create_post

        New User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
